### ISSUE TITLE
Error creating flow

### ISSUE THREAD

**Issue by KevinOleniczak** [sakazuki/aws-serverless-node-red#3]
trying this on windows...
node node_modules/.bin/node-red -s ./settings.js

results in error...
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by crushedy** [comment]
I installed it manually from the website, then I could run it with "node-red -s ./settings.js"
